export type RegionKey = "all" | "bali" | "jogja" | "jabar" | "jakarta" | "jatim";

export interface MediaLink {
  title: string;
  url: string;
  note_id?: string;
  note_en?: string;
}
export interface RoadshowLocation {
  date?: string; // format 2026-10-15, kosong = TBA
  gallery?: string[];
  mediaLinks?: MediaLink[];
  rsvpUrl?: string;
}
export interface RoadshowLocation {
  id: string;
  region: Exclude<RegionKey, "all">;
  name_id: string;
  name_en: string;
  date_id: string;
  date_en: string;
  time: string;
  address: string;
  lat: number;
  lng: number;
  category_id: string;
  category_en: string;
  desc_id: string;
  desc_en: string;
  feedback_id?: string;
  feedback_en?: string;
  imageText_id?: string;
  imageText_en?: string;
  thumbnailUrl?: string;
  mediaReleaseUrl?: string;
}

export const REGION_TABS: { key: RegionKey; label: string }[] = [
  { key: "all", label: "SEMUA" },
  { key: "jakarta", label: "JAKARTA" },
  { key: "jabar", label: "JAWA BARAT" },
  { key: "jogja", label: "DIY" },
  { key: "jatim", label: "JAWA TIMUR" },
  { key: "bali", label: "BALI" },
];

export const DEFAULT_CENTER: [number, number] = [-7.8, 111.5];
export const DEFAULT_ZOOM = 7;
export const FLY_TO_ZOOM = 16;

export const locationsData: RoadshowLocation[] = [
  // --- BALI ---
  {
    id: "sokasi",
    region: "bali",
    name_id: "Bale Banjar Sokasi Cafe Ubud",
    name_en: "Bale Banjar Sokasi Cafe Ubud",
    date_id: "20 Mei 2026",
    date_en: "May 20, 2026",
    time: "18.30 WITA",
    address: "Jl. Raya Kengetan, Singakerta, Ubud, Gianyar, Bali",
    lat: -8.528,
    lng: 115.253,
    category_id: "Hub Utama (Asal)",
    category_en: "Origin Hub (Home)",
    desc_id: "Penayangan perdana di tanah Bali (Genesis Screening). Menghadirkan sesi berbagi langsung bersama Made Bayak dan Gus Dark.",
    desc_en: "Genesis screening in Bali. Featuring a live sharing session with Balinese artivists Made Bayak and Gus Dark.",
    feedback_id: "Masyarakat dan seniman lokal Ubud menggarisbawahi pentingnya menjaga tanah air dan ekosistem subak dari ekspansi pariwisata yang tak terkendali.",
    feedback_en: "Local Ubud residents and artists emphasized the urgency of protecting native lands and subak ecosystems from unchecked tourism expansion.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "kulidan",
    region: "bali",
    name_id: "Kulidan Kitchen & Space",
    name_en: "Kulidan Kitchen & Space",
    date_id: "21 Mei & 3 Juni 2025",
    date_en: "May 21 & June 3, 2025",
    time: "17.30 WITA",
    address: "Banjar Wangbung, Sukawati, Gianyar, Bali",
    lat: -8.591,
    lng: 115.281,
    category_id: "Ruang Komunitas",
    category_en: "Community Space",
    desc_id: "Pemutaran komunitas di ruang publik kreatif Kulidan Space.",
    desc_en: "Community screening at Kulidan creative public space.",
    feedback_id: "Antusiasme warga lokal dan akademisi luar biasa merespons isu ekologi subak.",
    feedback_en: "Enthusiastic response from locals and academics regarding subak ecology issues.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "arma-museum",
    region: "bali",
    name_id: "ARMA Museum Ubud",
    name_en: "ARMA Museum Ubud",
    date_id: "25 Mei & 14 Juni 2025",
    date_en: "May 25 & June 14, 2025",
    time: "17.30 WITA",
    address: "Jl. Made Lebah, Mas, Ubud, Gianyar, Bali",
    lat: -8.5204,
    lng: 115.2638,
    category_id: "Museum & Galeri",
    category_en: "Museum & Gallery",
    desc_id: "Pemutaran film spesial yang dirangkaikan dengan pameran seni rupa ROOTS di ARMA Museum Ubud.",
    desc_en: "Special screening coupled with the ROOTS fine art exhibition at ARMA Museum Ubud.",
    feedback_id: "Diskusi yang sangat membuka ruang kritis baru tentang warisan sejarah Spies dan komodifikasi pariwisata Bali hari ini.",
    feedback_en: "Engaging discussion opening new critical discourse on Spies historical legacy.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
    mediaReleaseUrl: "https://kanalbali.id",
  },
  {
    id: "tamanbaca-kesiman",
    region: "bali",
    name_id: "Taman Baca Kesiman",
    name_en: "Taman Baca Kesiman",
    date_id: "27 Mei 2025",
    date_en: "May 27, 2025",
    time: "17.30 WITA",
    address: "Jl. Sedap Malam No. 234, Denpasar Timur, Bali",
    lat: -8.652,
    lng: 115.241,
    category_id: "Literasi & Budaya",
    category_en: "Literacy & Culture",
    desc_id: "Pemutaran dan diskusi publik mengenai dokumentasi sejarah dan lingkungan.",
    desc_en: "Screening and public discussion on history and environmental documentation.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "stikom-bali",
    region: "bali",
    name_id: "STIKOM Bali",
    name_en: "STIKOM Bali",
    date_id: "3 Juni 2025",
    date_en: "June 3, 2025",
    time: "13.30 WITA",
    address: "Jl. Raya Puputan No. 86, Denpasar Timur, Bali",
    lat: -8.671,
    lng: 115.231,
    category_id: "Kampus",
    category_en: "Campus",
    desc_id: "Pemutaran khusus akademis dan mahasiswa teknologi media.",
    desc_en: "Academic screening for media technology students.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "uma-seminyak",
    region: "bali",
    name_id: "Uma Seminyak",
    name_en: "Uma Seminyak",
    date_id: "3 Juni 2025",
    date_en: "June 3, 2025",
    time: "17.30 WITA",
    address: "Jl. Kayu Cendana Oberoi No. 1, Seminyak, Badung, Bali",
    lat: -8.687,
    lng: 115.156,
    category_id: "Hub Kreatif",
    category_en: "Creative Hub",
    desc_id: "Penayangan di ruang gaya hidup dan seni kreatif kawasan Seminyak.",
    desc_en: "Screening at a lifestyle and creative art space in Seminyak.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "danes-art",
    region: "bali",
    name_id: "Danes Art Veranda",
    name_en: "Danes Art Veranda",
    date_id: "2025–2026",
    date_en: "2025–2026",
    time: "TBA",
    address: "Jl. Hayam Wuruk No. 159, Denpasar, Bali",
    lat: -8.662,
    lng: 115.235,
    category_id: "Galeri Arsitektur & Seni",
    category_en: "Architecture & Art Gallery",
    desc_id: "Pemutaran dan dialog arsitektur serta ruang budaya Bali.",
    desc_en: "Screening and architectural dialogue on Balinese cultural space.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "isi-bali",
    region: "bali",
    name_id: "Institut Seni Indonesia (ISI) Bali",
    name_en: "ISI Bali",
    date_id: "2025–2026",
    date_en: "2025–2026",
    time: "TBA",
    address: "Jl. Nusa Indah, Sumerta Pertapaan, Denpasar, Bali",
    lat: -8.655,
    lng: 115.233,
    category_id: "Kampus Seni",
    category_en: "Art Academy",
    desc_id: "Sesi ceramah umum dan pemutaran untuk mahasiswa seni Bali.",
    desc_en: "Public lecture and screening session for Balinese art students.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "wiisp",
    region: "bali",
    name_id: "WIISP 2025 (Warmadewa Studies)",
    name_en: "WIISP 2025 (Warmadewa Studies)",
    date_id: "2025",
    date_en: "2025",
    time: "TBA",
    address: "Perama Hotel, Denpasar, Bali",
    lat: -8.681,
    lng: 115.212,
    category_id: "Simposium Internasional",
    category_en: "International Symposium",
    desc_id: "Pemutaran interdisipliner bagian dari program Warmadewa International.",
    desc_en: "Interdisciplinary screening part of Warmadewa International Program.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },

  // --- YOGYAKARTA / DIY ---
  {
    id: "bsrjogja",
    region: "jogja",
    name_id: "Buku Seni Rupa – We Love You(th)",
    name_en: "Buku Seni Rupa – We Love You(th)",
    date_id: "7 Mei 2026",
    date_en: "May 7, 2026",
    time: "18.30 WIB",
    address: "Jl. Babar Rejo No. 5, Krapyak, Wedomartani, Ngemplak, Sleman, DIY",
    lat: -7.741,
    lng: 110.412,
    category_id: "Ruang Komunitas",
    category_en: "Community Space",
    desc_id: "Diskusi mendalam menghadirkan Jean-Pascal Elbaz dan Made Bayak dipandu moderator Nurul Nelwan.",
    desc_en: "In-depth discussion featuring Jean-Pascal Elbaz and Made Bayak, moderated by Nurul Nelwan.",
    feedback_id: "Diskusi hangat mengenai aktivisme ekologi Made Bayak dan dampaknya bagi kesadaran generasi muda di Jogja.",
    feedback_en: "Engaging dialogue on Made Bayak's ecological activism and its impact on youth awareness in Jogja.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "isijogja",
    region: "jogja",
    name_id: "FSRD ISI Yogyakarta",
    name_en: "FSRD ISI Yogyakarta",
    date_id: "8 Mei 2026",
    date_en: "May 8, 2026",
    time: "13.30 WIB",
    address: "Sasana Ajiyasa Lt. 2 FSRD ISI Yogyakarta, Sewon, Bantul, DIY",
    lat: -7.852,
    lng: 110.358,
    category_id: "Kampus Seni",
    category_en: "Art Academy",
    desc_id: "Dibuka oleh Dekan FSRD ISI Yogyakarta Muhamad Sholahuddin, S.Sn., M.T dengan pembicara Yudha Bantono & Wiwik Sri Wulandari, M.Sn.",
    desc_en: "Opened by Dean Muhamad Sholahuddin with keynote talks by Yudha Bantono & Wiwik Sri Wulandari.",
    feedback_id: "Mahasiswa seni rupa membedah semiotika lukisan Spies serta kontras estetika poros Yogyakarta - Bali.",
    feedback_en: "Art students analyzed Spies painting semiotics and the aesthetic contrast between Yogyakarta and Bali.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "yamiebd",
    region: "jogja",
    name_id: "Yamie Bang Doel Bantul",
    name_en: "Yamie Bang Doel Bantul",
    date_id: "9 Mei 2026",
    date_en: "May 9, 2026",
    time: "18.30 WIB",
    address: "Jl. Industri 2 Gunung Sempu, Tamantirto, Kasihan, Bantul, DIY",
    lat: -7.8385,
    lng: 110.345,
    category_id: "Ruang Alternatif",
    category_en: "Alternative Space",
    desc_id: "Pemutaran santai hosted by Andry Boy di ruang kumpul komunitas Bantul.",
    desc_en: "Casual screening hosted by Andry Boy in a local Bantul community gathering venue.",
    feedback_id: "Apresiasi audiens terhadap format pemutaran di ruang komunal yang mendekatkan isu sejarah ke publik luas.",
    feedback_en: "Audience appreciated the relaxed communal setting that made historical discourse accessible.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "ohd-museum",
    region: "jogja",
    name_id: "OHD Museum Magelang",
    name_en: "OHD Museum Magelang",
    date_id: "10 Mei 2026",
    date_en: "May 10, 2026",
    time: "15.00 WIB",
    address: "Jl. Jenggolo No. 14, Magelang Tengah, Kota Magelang",
    lat: -7.472,
    lng: 110.218,
    category_id: "Museum Seni Rupa",
    category_en: "Art Museum",
    desc_id: "Pemutaran khusus di museum koleksi seni rupa Indonesia ternama milik Dr. Oei Hong Djien.",
    desc_en: "Special screening at Dr. Oei Hong Djien private fine art museum.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "museum-widayat",
    region: "jogja",
    name_id: "Museum H. Widayat",
    name_en: "Museum H. Widayat",
    date_id: "12 Mei 2026",
    date_en: "May 12, 2026",
    time: "18.30 WIB",
    address: "Jl. Soekarno Hatta No. 32, Sawitan, Mungkid, Kab. Magelang",
    lat: -7.561,
    lng: 110.231,
    category_id: "Museum Seni",
    category_en: "Art Museum",
    desc_id: "Penayangan film di museum maestro Widayat Mungkid Magelang.",
    desc_en: "Screening at maestro Widayat museum complex in Mungkid Magelang.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },

  // --- JAWA BARAT ---
  {
    id: "humanika",
    region: "jabar",
    name_id: "Humanika Artspace Bandung",
    name_en: "Humanika Artspace Bandung",
    date_id: "29 Juli 2026",
    date_en: "July 29, 2026",
    time: "19.00 WIB",
    address: "Perumahan Jl. Bojong Koneng No. 87 Kav 75, Cibeunying, Kab. Bandung",
    lat: -6.885,
    lng: 107.641,
    category_id: "Ruang Seni Kreatif",
    category_en: "Creative Artspace",
    desc_id: "Kick-off penayangan rute Tour de Java Jawa Barat di ruang seni independen kawasan Cibeunying.",
    desc_en: "Kick-off screening for West Java Tour de Java at an independent art space in Cibeunying.",
    feedback_id: "Membuka rangkaian diskusi kritis perupa muda Bandung mengenai dekonstruksi eksotisme kolonial.",
    feedback_en: "Initiated critical discussions among young Bandung artists deconstructing colonial exoticism.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "orbitaldago",
    region: "jabar",
    name_id: "Orbital Dago Bandung",
    name_en: "Orbital Dago Bandung",
    date_id: "30 Juli 2026",
    date_en: "July 30, 2026",
    time: "16.00 WIB",
    address: "Jl. Rancakendal No. 7, Cigadung, Cibeunying Kaler, Kota Bandung",
    lat: -6.872,
    lng: 107.625,
    category_id: "Galeri Kontemporer",
    category_en: "Contemporary Gallery",
    desc_id: "Penayangan di ruang seni kontemporer ternama di kawasan Dago Pakar.",
    desc_en: "Screening at a renowned contemporary art gallery in Dago Pakar, Bandung.",
    feedback_id: "Apresiasi tinggi dari praktisi seni rupa Bandung terhadap pendekatan dokumenter fiksi Schindhelm.",
    feedback_en: "High acclaim from Bandung art practitioners regarding Schindhelm docu-fiction approach.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "nuart",
    region: "jabar",
    name_id: "NuArt Sculpture Park Bandung",
    name_en: "NuArt Sculpture Park Bandung",
    date_id: "31 Juli 2026",
    date_en: "July 31, 2026",
    time: "16.00 WIB",
    address: "Jl. Setra Duta Raya No. L 6, Bandung, Jawa Barat",
    lat: -6.8785,
    lng: 107.574,
    category_id: "Taman Patung & Galeri",
    category_en: "Sculpture Park & Gallery",
    desc_id: "Penayangan di komplek galeri patung maestro Nyoman Nuarta di Bandung.",
    desc_en: "Screening hosted within maestro Nyoman Nuarta sculpture park complex in Bandung.",
    feedback_id: "Refleksi mendalam mengenai hubungan antara seni patung monumental dan ruang terbuka hijau.",
    feedback_en: "Profound reflection on the relationship between monumental sculpture and green open spaces.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "langgaraksara",
    region: "jabar",
    name_id: "Langgar Aksara Nusantara Depok",
    name_en: "Langgar Aksara Nusantara Depok",
    date_id: "4 Agustus 2026",
    date_en: "Aug 4, 2026",
    time: "16.00 WIB",
    address: "Jl. Kyai Si'an No. 11, Pengasinan, Sawangan, Kota Depok",
    lat: -6.415,
    lng: 106.748,
    category_id: "Pusat Kebudayaan",
    category_en: "Cultural Center",
    desc_id: "Pemutaran berkonsep joglo kebudayaan di kawasan Pengasinan Depok.",
    desc_en: "Cultural screening at a traditional joglo heritage hub in Sawangan, Depok.",
    feedback_id: "Diskusi hangat mengenai titik temu tradisi lisan, arsitektur lokal, dan pelestarian budaya.",
    feedback_en: "Lively dialogue on oral traditions, local architecture, and cultural preservation.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "hutanrimba",
    region: "jabar",
    name_id: "Hutan Rimba Bogor",
    name_en: "Hutan Rimba Bogor",
    date_id: "6 Agustus 2026",
    date_en: "Aug 6, 2026",
    time: "18.30 WIB",
    address: "Jl. Raya Pondok Bitung, Sukaharja, Cijeruk, Kab. Bogor",
    lat: -6.685,
    lng: 106.802,
    category_id: "Ruang Alam Outdoor",
    category_en: "Nature Outdoor Space",
    desc_id: "Penayangan di area ruang terbuka hijau dan alam kaki Gunung Salak Cijeruk Bogor.",
    desc_en: "Outdoor nature screening at the foot of Mount Salak in Cijeruk, Bogor.",
    feedback_id: "Suasana outdoor memperkuat resonansi pesan ekologis dan kelestarian alam dalam film ROOTS.",
    feedback_en: "Atmospheric outdoor venue amplified the ecological and environmental themes of ROOTS.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },

  // --- JAKARTA ---
  {
    id: "gruham",
    region: "jakarta",
    name_id: "Gruham Coffee & Bistro",
    name_en: "Gruham Coffee & Bistro",
    date_id: "3 Mei 2026",
    date_en: "May 3, 2026",
    time: "15.00 WIB",
    address: "Jl. Panglima Polim V No. 21, Melawai, Jakarta Selatan",
    lat: -6.244,
    lng: 106.797,
    category_id: "Ruang Alternatif",
    category_en: "Alternative Space",
    desc_id: "Pemutaran edisi spesial Jakarta yang menggabungkan tayangan film dengan Watercolor Workshop bersama perupa cat air Agus Budiyanto.",
    desc_en: "Special Jakarta screening combining film presentation with a watercolor workshop by Agus Budiyanto.",
    feedback_id: "Penggabungan antara lokakarya melukis merespons karya Spies dengan diskusi sejarah seni membuat impresi visual terasa lebih mendalam.",
    feedback_en: "Combining watercolor art workshop responding to Spies work with historical discourse created deep engagement.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "getback",
    region: "jakarta",
    name_id: "Getback Parlour Fatmawati",
    name_en: "Getback Parlour Fatmawati",
    date_id: "1 Agustus 2026",
    date_en: "Aug 1, 2026",
    time: "16.00 WIB",
    address: "Dutamas Blok B2/12 ITC Fatmawati, Jakarta Selatan",
    lat: -6.275,
    lng: 106.796,
    category_id: "Hub Kreatif",
    category_en: "Creative Hub",
    desc_id: "Pembuka leg Jakarta di Fatmawati Jakarta Selatan.",
    desc_en: "Opening leg for Jakarta screenings at Fatmawati, South Jakarta.",
    feedback_id: "Dihadiri komunitas kreatif muda Jakarta Selatan dengan antusiasme pada isu pariwisata massal.",
    feedback_en: "Attended by South Jakarta creative communities passionate about mass tourism critique.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "tim",
    region: "jakarta",
    name_id: "Taman Ismail Marzuki (TIM)",
    name_en: "Taman Ismail Marzuki (TIM)",
    date_id: "2 Agustus 2026",
    date_en: "Aug 2, 2026",
    time: "17.00 WIB",
    address: "Jl. Cikini Raya No. 8, Menteng, Jakarta Pusat",
    lat: -6.1898,
    lng: 106.8398,
    category_id: "Pusat Kebudayaan",
    category_en: "Public Cultural Center",
    desc_id: "Penayangan di pusat kebudayaan publik Jakarta. Menarik minat pengamat film dokumenter dan komunitas teater.",
    desc_en: "Screening at Jakarta public cultural landmark. Attracted documentary analysts and theater groups.",
    feedback_id: "Diskusi hangat mengenai struktur narasi docu-fiction dan penggunaan karakter hantu Spies sebagai alat pemantul refleksi.",
    feedback_en: "Vibrant discussion on docu-fiction storytelling and using Spies ghost persona as a reflective tool.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "tmii",
    region: "jakarta",
    name_id: "Contemporary Art Gallery TMII",
    name_en: "Contemporary Art Gallery TMII",
    date_id: "3 Agustus 2026",
    date_en: "Aug 3, 2026",
    time: "15.30 WIB",
    address: "Taman Mini Indonesia Indah, Jakarta Timur",
    lat: -6.302,
    lng: 106.895,
    category_id: "Galeri Kontemporer",
    category_en: "Contemporary Gallery",
    desc_id: "Pemutaran di galeri seni kontemporer kompleks TMII Jakarta Timur.",
    desc_en: "Screening at the contemporary art gallery inside TMII park complex.",
    feedback_id: "Pembahasan mendalam tentang reposisi museum seni dalam merespons karya-karya era kolonial.",
    feedback_en: "Thoughtful analysis on repositioning art museums to address colonial era artworks.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "zen1",
    region: "jakarta",
    name_id: "Galeri Zen1 Menteng",
    name_en: "Galeri Zen1 Menteng",
    date_id: "5 Agustus 2026",
    date_en: "Aug 5, 2026",
    time: "16.00 WIB",
    address: "Jl. Purworejo No. 24, Menteng, Jakarta Pusat",
    lat: -6.199,
    lng: 106.824,
    category_id: "Galeri Komersial",
    category_en: "Commercial Gallery",
    desc_id: "Pemutaran intim di galeri seni komersial kawasan Menteng.",
    desc_en: "Intimate screening at a commercial art gallery in Menteng.",
    feedback_id: "Apresiasi dari para kolektor seni rupa dan pengamat estetik Jakarta.",
    feedback_en: "Highly appreciated by fine art collectors and aesthetic critics in Jakarta.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "cemara6",
    region: "jakarta",
    name_id: "Cemara 6 Galeri - Toeti Heraty Museum",
    name_en: "Cemara 6 Galeri - Toeti Heraty Museum",
    date_id: "7 Agustus 2026",
    date_en: "Aug 7, 2026",
    time: "14.00 WIB",
    address: "Jl. HOS. Cokroaminoto No. 9-11, Menteng, Jakarta Pusat",
    lat: -6.1955,
    lng: 106.8315,
    category_id: "Museum & Galeri",
    category_en: "Museum & Gallery",
    desc_id: "Pemutaran penutup untuk tur 12 hari nonstop Jawa Barat - Jakarta. Dihadiri oleh Direktur Galeri Ibu Inda C. Noerhadi serta jajaran budayawan.",
    desc_en: "Grand finale for the 12-day non-stop West Java-Jakarta tour, attended by Director Ibu Inda C. Noerhadi and scholars.",
    feedback_id: "Audiens sangat mengapresiasi dialog kritis mengenai perlindungan cagar budaya dan reposisi museum seni di era pariwisata modern.",
    feedback_en: "Audience lauded the dialogue on heritage protection and museum repositioning in modern tourism.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },

  // --- JAWA TIMUR ---
  {
    id: "serakit",
    region: "jatim",
    name_id: "Studio Serakit Jember",
    name_en: "Studio Serakit Jember",
    date_id: "29 Agustus 2026",
    date_en: "Aug 29, 2026",
    time: "19.30 WIB",
    address: "Jl. Koptu Berlian, Jambutan, Antirogo, Jember",
    lat: -8.142,
    lng: 113.725,
    category_id: "Ruang Alternatif",
    category_en: "Alternative Space",
    desc_id: "Pembuka leg Jawa Timur di studio independen kawasan Jember.",
    desc_en: "Opening screening for the East Java leg at an independent studio in Jember.",
    feedback_id: "Respon positif komunitas film independen Jember terhadap eksperimentasi docu-fiction.",
    feedback_en: "Warm response from Jember indie film community towards docu-fiction narrative style.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "museumhuruf",
    region: "jatim",
    name_id: "Museum Huruf Jember",
    name_en: "Museum Huruf Jember",
    date_id: "31 Agustus 2026",
    date_en: "Aug 31, 2026",
    time: "15.00 WIB",
    address: "Jl. Bengawan Solo No. 27, Tegal Boto Lor, Jember",
    lat: -8.165,
    lng: 113.712,
    category_id: "Museum Literasi",
    category_en: "Literacy Museum",
    desc_id: "Pemutaran berorientasi literasi dan aksara sejarah di Museum Huruf Jember.",
    desc_en: "Literacy and historical script-oriented screening at Museum Huruf Jember.",
    feedback_id: "Diskusi seputar semiotika tulisan dan dokumentasi arsip sejarah era 1930-an.",
    feedback_en: "Discussion exploring textual semiotics and 1930s historical archival records.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "banyuwangi",
    region: "jatim",
    name_id: "Disbudpar Kabupaten Banyuwangi",
    name_en: "Disbudpar Banyuwangi Office",
    date_id: "1 & 2 September 2026",
    date_en: "Sep 1-2, 2026",
    time: "08.30 WIB",
    address: "Jl. Jenderal Ahmad Yani No. 78, Taman Baru, Banyuwangi",
    lat: -8.2192,
    lng: 114.3691,
    category_id: "Institusi Pemerintah",
    category_en: "Government Authority",
    desc_id: "Penayangan resmi bekerja sama dengan Dinas Kebudayaan dan Pariwisata Banyuwangi.",
    desc_en: "Official screening co-hosted with Banyuwangi Culture and Tourism Office.",
    feedback_id: "Memberikan wawasan krusial bagi penyusunan roadmap pariwisata daerah yang berwawasan lingkungan dan menjaga tradisi lokal.",
    feedback_en: "Provided key insights for regional tourism roadmap planning focusing on sustainability and tradition.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "stkw",
    region: "jatim",
    name_id: "STKW Surabaya (Wilwatikta College)",
    name_en: "STKW Surabaya (Wilwatikta College)",
    date_id: "5 September 2026",
    date_en: "Sep 5, 2026",
    time: "09.00 WIB",
    address: "Jl. Klampis Anom II, Sukolilo, Surabaya",
    lat: -7.2885,
    lng: 112.776,
    category_id: "Kampus Seni",
    category_en: "Art College",
    desc_id: "Pemutaran akademis di kampus seni pertunjukan dan seni rupa tertua di Jawa Timur.",
    desc_en: "Academic screening at East Java oldest performing and visual arts college.",
    feedback_id: "Bedah estetika tari dan musik gamelan Bali yang dipengaruhi interaksi Walter Spies pada dekade 1930-an.",
    feedback_en: "Deep dive into Balinese dance and gamelan aesthetics influenced by Walter Spies in the 1930s.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
  {
    id: "zumenart",
    region: "jatim",
    name_id: "Zumenart Purimas Surabaya",
    name_en: "Zumenart Purimas Surabaya",
    date_id: "6 September 2026",
    date_en: "Sep 6, 2026",
    time: "13.30 WIB",
    address: "Perumahan Purimas, Gunung Anyar, Surabaya",
    lat: -7.3312,
    lng: 112.7845,
    category_id: "Akademi Seni Muda",
    category_en: "Youth Art Academy",
    desc_id: "Leg akhir (final stop) dari Tour de Java. Menghadirkan pameran seni kolaboratif perupa muda Faith Shamayim bersama Gen Z.",
    desc_en: "Final leg stop of the Tour de Java. Featuring collaborative art exhibition by young artist Faith Shamayim and Gen Z.",
    feedback_id: "Antusiasme luar biasa dari generasi muda seni Rupa Surabaya dengan diskusi kritis seputar cara orang Bali merespons pendatang asing.",
    feedback_en: "Tremendous Gen Z enthusiasm exploring how Balinese society responds to foreign cultural influences.",
    thumbnailUrl: "https://michaelschindhelm.com/wp-content/uploads/2024/05/ROOTS_Arma.jpg",
  },
];

export type ScreeningStatus = "upcoming" | "finished" | "tba";
export type StatusFilter = "all" | "upcoming" | "finished";

// Tanggal hari ini di WIB, format 2026-09-24
export function todayISO() {
  return new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Jakarta" });
}

export function getStatus(loc: { date?: string }, today: string): ScreeningStatus {
  if (!loc.date) return "tba";
  return loc.date < today ? "finished" : "upcoming";
}
